# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "starstruck"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "xtask",
]

[[bin]]
name = "router"
path = "src/router/main.rs"

[[bin]]
name = "helper"
path = "src/helper/main.rs"

[dependencies]
# Note if you update these dependencies then also update xtask/Cargo.toml
anyhow = "1.0.58"
actix-web = "4"
apollo-router = { git = "https://github.com/sushant3524/router.git", branch = "router-ignore-validation" }
async-trait = "0.1.52"
futures = "0.3.21"
schemars = "0.8.10"
serde = "1.0.149"
serde_json = "1.0.79"
tower = { version = "0.4.12", features = ["full"] }
tracing = "0.1.37"
http = "0.2.12"
cached  = "0.51.3"
tokio = { version = "1.17.0", features = ["full"] }
once_cell = "1.19.0"
reqwest = "0.11.27"

[alias]
xtask = "run --package xtask --"
router = "run --package xtask -- router"


# this makes build scripts and proc macros faster to compile
[profile.dev.build-override]
strip = "debuginfo"
incremental = false

[dependencies.mongodb]
version = "2.8.2"
default-features = false
features = ["sync"]
