federation_version: =2.8.1
subgraphs:
  process-engine:
    routing_url: https://qa6-process-engine-tier1.sprinklr.com/graphql/
    schema:
      file: ./process-engine.graphql
  webui:
    routing_url: https://space-qa6-care.sprinklr.com/ui/graphql
    schema:
      file: ./webui.graphql
  voice:
    routing_url: https://qa6-voice-tier1.sprinklr.com/graphql/
    schema:
      file: ./voice.graphql